"""Regenerate Paper B Tables 1-2 from committed evidence (reproducibility).

  tables/tab_spacecraft.tex  Domain 1 coverage vs heuristic (conformal_rta.json)
  tables/tab_pendulum.tex    Domain 2 engagement-rule comparison (pendulum_domain.json)

So every number in Paper B's tables re-derives from a producer's evidence, matching the
Paper A discipline. Run from paper/conformal/ with `python tables.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPACE = json.loads((ROOT / "evidence/program/conformal_rta.json").read_text())
PEND = json.loads((ROOT / "evidence/conformal_cert/pendulum_domain.json").read_text())
TBL = Path(__file__).resolve().parent / "tables"
TBL.mkdir(exist_ok=True)


def _spacecraft() -> str:
    rows = ""
    for c in SPACE["certificates"]:
        a, tgt, cov = c["alpha"], c["target_coverage"], c["mean_conformal_coverage"]
        d, s = c["median_conformal_deadline_steps"], c["median_conformal_deadline_s"]
        rows += f"{a:.2f} & {tgt:.2f} & {cov:.3f} & {d} steps ({s:.1f} s) \\\\\n"
    return (
        "% AUTO-GENERATED by paper/conformal/tables.py from conformal_rta.json\n"
        "\\begin{table}[h]\\centering\\small\n"
        "\\caption{Domain 1 (spacecraft). Split-conformal deadline coverage vs.\\ the "
        "heuristic, over 300 calibration/test splits of held-out gain faults.}\n"
        "\\label{tab:spacecraft}\n"
        "\\begin{tabular}{lccc}\n\\toprule\n"
        "$\\alpha$ & target $1-\\alpha$ & conformal mean coverage & median deadline \\\\\n"
        "\\midrule\n" + rows + "\\midrule\n"
        "\\multicolumn{4}{l}{\\footnotesize heuristic $p95\\times1.3$ gives ${\\sim}0.97$ "
        "coverage at every target (no guarantee, not tunable)} \\\\\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )


def _pendulum() -> str:
    b = PEND["baselines_B4"]
    order = [
        ("latching_simplex", "Latching Simplex", "none (the pathology)"),
        ("heuristic_p95x1.3", "Heuristic $p95\\times1.3$", "none (over-covers)"),
        (
            "cp_safety_value",
            "CP-on-safety-value~\\cite{Tabbara2025}",
            "$1-\\alpha$ on peak $|\\theta|$",
        ),
        (
            "conformal_recovery_deadline_ours",
            "\\textbf{Conformal recovery-deadline (ours)}",
            "$1-\\alpha$ on recovery time",
        ),
    ]
    rows = ""
    for key, label, guar in order:
        r = b[key]
        auto = 100 * r["autonomy_retention"]
        caught = 100 * r["divergence_caught_before_critical"]
        ttc = r["mean_time_to_catch_steps"]
        rows += f"{label} & {auto:.1f}\\% & {caught:.0f}\\% & {ttc:.1f} steps & {guar} \\\\\n"
    return (
        "% AUTO-GENERATED by paper/conformal/tables.py from pendulum_domain.json\n"
        "\\begin{table}[h]\\centering\\footnotesize\n"
        "\\caption{Domain 2 (pendulum). RTA engagement rules on the reversal regime, reporting "
        "autonomy retention on the capable adapting controller, divergence caught (before the "
        "verified backstop) on the fault-unaware controller, mean time-to-catch, and coverage "
        "guarantee.}\n"
        "\\label{tab:pend}\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\begin{tabular}{lcccl}\n\\toprule\n"
        "Engagement rule & autonomy & divergence caught & time-to-catch & coverage guarantee \\\\\n"
        "\\midrule\n" + rows + "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )


def main() -> None:
    (TBL / "tab_spacecraft.tex").write_text(_spacecraft(), encoding="utf-8")
    (TBL / "tab_pendulum.tex").write_text(_pendulum(), encoding="utf-8")
    print(f"wrote 2 tables to {TBL}")


if __name__ == "__main__":
    main()
